# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Askai < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/askai/releases/download/v0.1.1/askai_Darwin_arm64.tar.gz"
      sha256 "3b820aaf45241386ef3fd42ded42923788fa1142805f09aa647f79d1ce16d28f"

      def install
        bin.install "askai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/askai/releases/download/v0.1.1/askai_Darwin_x86_64.tar.gz"
      sha256 "bc2777ce6e66073320474652f8185eba9894ad9e210e2775310667294bd3de0a"

      def install
        bin.install "askai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/askai/releases/download/v0.1.1/askai_Linux_arm64.tar.gz"
      sha256 "61497aa6a9e05e9cc9f80cbf678bf06ab22291c2c427229f87b1c76a5ce5ccfa"

      def install
        bin.install "askai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/askai/releases/download/v0.1.1/askai_Linux_x86_64.tar.gz"
      sha256 "11cc9b8dcf7cbf4081918bcfcbea43d0d65e6a402d61f4447dc7efa6e7fe2ac2"

      def install
        bin.install "askai"
      end
    end
  end
end
