# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Askai < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/askai/releases/download/v0.1.0/askai_Darwin_arm64.tar.gz"
      sha256 "be258c87553af099218f2e4d1d83c8c9567e6c7c680c5ee0f58521728321976d"

      def install
        bin.install "askai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/askai/releases/download/v0.1.0/askai_Darwin_x86_64.tar.gz"
      sha256 "c1dffbeb7b16474c0aaebdbdaf76f3c24414483e34d134fbf2fe3766d719bea0"

      def install
        bin.install "askai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/askai/releases/download/v0.1.0/askai_Linux_x86_64.tar.gz"
      sha256 "8ab8fa890e92ec5d2fc6cf8240a7fb557e6b980480e31fed2ad260f261ad09e3"

      def install
        bin.install "askai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/askai/releases/download/v0.1.0/askai_Linux_arm64.tar.gz"
      sha256 "0a821c203b75b1b0943f6e75d0cdf87f28e4b75164655c7c2da60118a802c894"

      def install
        bin.install "askai"
      end
    end
  end
end
