# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ego < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/ego/releases/download/v0.2.0/ego_Darwin_x86_64.tar.gz"
      sha256 "7d7bde827199a21a306844ecea4b80f37a46508f692d98c6b14b7473c91454c8"

      def install
        bin.install "ego"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/ego/releases/download/v0.2.0/ego_Darwin_arm64.tar.gz"
      sha256 "48543ff48534368d7036f286039511ebcd82d63728c33295f88d3700cf2c9864"

      def install
        bin.install "ego"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/ego/releases/download/v0.2.0/ego_Linux_x86_64.tar.gz"
      sha256 "a750e00187e85f457897b0af38520bec970b844680d1478014dd4a43fe8c6bd1"

      def install
        bin.install "ego"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/ego/releases/download/v0.2.0/ego_Linux_arm64.tar.gz"
      sha256 "5ec3976201bd880ed562467dc40572d2f856d5c34986601f52ceac70254dc2a7"

      def install
        bin.install "ego"
      end
    end
  end
end
