# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ego < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/ego/releases/download/v0.1.0/ego_Darwin_x86_64.tar.gz"
      sha256 "884efe8283cb44412a263f4c80c19b22e4e6113e6a36024fde1b9ffb59a22830"

      def install
        bin.install "ego"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/ego/releases/download/v0.1.0/ego_Darwin_arm64.tar.gz"
      sha256 "98a6480d3aa9e06586092413071f7ee17220640e6c3f2acd7c3f39258f5fa524"

      def install
        bin.install "ego"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/ego/releases/download/v0.1.0/ego_Linux_arm64.tar.gz"
      sha256 "d78d56a109402465e4e4cf2063763fbb2dbd10eb370ec20c06388497e359dfb5"

      def install
        bin.install "ego"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/ego/releases/download/v0.1.0/ego_Linux_x86_64.tar.gz"
      sha256 "0fbbd3bc329ba4203509f8ef51a912fb1ab2a472e0bbd0d74835ea4153f79564"

      def install
        bin.install "ego"
      end
    end
  end
end
