# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFzf < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.2.0/go-fzf_Darwin_x86_64.tar.gz"
      sha256 "c34caa46ad281f4a41f5ba13bf0cddc88e3239d6818e83ea37fbc2c75ce697b3"

      def install
        bin.install "go-fzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.2.0/go-fzf_Darwin_arm64.tar.gz"
      sha256 "82bc801dee823724ae12162f8a231a6023c0fd017159ec4f3340b0c3076481a4"

      def install
        bin.install "go-fzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.2.0/go-fzf_Linux_x86_64.tar.gz"
      sha256 "0ee88f9ab711320303e1ec39718380006e3172482047527750e6b4376c1aafe4"

      def install
        bin.install "go-fzf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.2.0/go-fzf_Linux_arm64.tar.gz"
      sha256 "478659f9479b2a34595aa05f6a0cb0767a85bddac8da20c346339ef7cee0b179"

      def install
        bin.install "go-fzf"
      end
    end
  end
end
