# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofzf < Formula
  desc ""
  homepage ""
  version "0.13.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.13.2/gofzf_Darwin_x86_64.tar.gz"
      sha256 "7154eedd95a502b8126c6e1fca232f4ebe7dcac91dbced75b37a000ecec45227"

      def install
        bin.install "gofzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.13.2/gofzf_Darwin_arm64.tar.gz"
      sha256 "acb97785979a12228dd67f8b993772aeb9f3db933e46a63ca36be0b0b9f79987"

      def install
        bin.install "gofzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.13.2/gofzf_Linux_arm64.tar.gz"
      sha256 "f4f55720df087f8c74ce66b2fbdb16e8005cb0625605a8463eb47365158d55f8"

      def install
        bin.install "gofzf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.13.2/gofzf_Linux_x86_64.tar.gz"
      sha256 "cfdf35b048a40cd7ff166e42df2056e7c34adeba6b613b70345a1ccdeb0f1780"

      def install
        bin.install "gofzf"
      end
    end
  end
end
