# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofzf < Formula
  desc ""
  homepage ""
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.5.1/gofzf_Darwin_x86_64.tar.gz"
      sha256 "1de9994ca0572661a48db05c7815655be9c439a3e252d28786efc2e15858c36a"

      def install
        bin.install "gofzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.5.1/gofzf_Darwin_arm64.tar.gz"
      sha256 "59ee2158c22f841de08d22fa348915ebbac1955be30b0e5da077b1fbc61af783"

      def install
        bin.install "gofzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.5.1/gofzf_Linux_arm64.tar.gz"
      sha256 "c7e9ef72d18b97aa6b4c3710e9f75aff70e9c6de91c9ce47de046bf80b774aff"

      def install
        bin.install "gofzf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.5.1/gofzf_Linux_x86_64.tar.gz"
      sha256 "29e0e5f2f6854852d6210f04ed60e09877525067bf8713ea0114ecbb516e5635"

      def install
        bin.install "gofzf"
      end
    end
  end
end
