# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofzf < Formula
  desc ""
  homepage ""
  version "0.14.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.14.2/gofzf_Darwin_x86_64.tar.gz"
      sha256 "6b76fddb29632592c7621279ff30c18a1ac7be01c571022f98981081dd2064f9"

      def install
        bin.install "gofzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.14.2/gofzf_Darwin_arm64.tar.gz"
      sha256 "ce224868b54188f211ac10e04185078f0b97014812c4e1584c9488b575dd09ce"

      def install
        bin.install "gofzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.14.2/gofzf_Linux_arm64.tar.gz"
      sha256 "5faf9fad9b3dddcfa1400fb7a52c79b8c71d9242d0005c9806d03ddb17bd56a5"

      def install
        bin.install "gofzf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.14.2/gofzf_Linux_x86_64.tar.gz"
      sha256 "5b1c59d55fd90a60a6f58e19ddf4817c054ae6c0fa91c6e8c639dbfcb04bf5d3"

      def install
        bin.install "gofzf"
      end
    end
  end
end
