# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonvert < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gonvert/releases/download/v0.1.0/gonvert_Darwin_x86_64.tar.gz"
      sha256 "1db950c2a5f5e1764b269f68ad3dcfdcd0723ea1f89738c16dc488aaced58d4d"

      def install
        bin.install "gonvert"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/gonvert/releases/download/v0.1.0/gonvert_Darwin_arm64.tar.gz"
      sha256 "72306d9e4cd940725c5062ea569e50e2506faa233c35a67ffdceb0872dc672bb"

      def install
        bin.install "gonvert"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gonvert/releases/download/v0.1.0/gonvert_Linux_arm64.tar.gz"
      sha256 "1ac3035dec9817a3945a49f5edb17466be9d5789fb8710bb3fc8a9f063124746"

      def install
        bin.install "gonvert"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gonvert/releases/download/v0.1.0/gonvert_Linux_x86_64.tar.gz"
      sha256 "09effbd2670ec9aa3d49a9d69fc799c29cc6410f527f8af7da523679aeda62f0"

      def install
        bin.install "gonvert"
      end
    end
  end
end
