# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonvert < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/gonvert/releases/download/v0.1.1/gonvert_Darwin_arm64.tar.gz"
      sha256 "f5eff4a276270dc1863266b41930df5f28369b1c1523b0a224ab3006ca61e627"

      def install
        bin.install "gonvert"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gonvert/releases/download/v0.1.1/gonvert_Darwin_x86_64.tar.gz"
      sha256 "f53c0de42bb30804c70c89d4c4f230fe1a520ffc985cead0af9790dae7cf810f"

      def install
        bin.install "gonvert"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gonvert/releases/download/v0.1.1/gonvert_Linux_x86_64.tar.gz"
      sha256 "719c0256d86dd67cd02cc9b3e69eda7c7983f9d28a8857db30d9e8b0c66b1f38"

      def install
        bin.install "gonvert"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gonvert/releases/download/v0.1.1/gonvert_Linux_arm64.tar.gz"
      sha256 "4b5fe127b6e0c10e842070f8e2fee02553d52022f8d6bd6dec966bc7503ac405"

      def install
        bin.install "gonvert"
      end
    end
  end
end
