# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotrash < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.2.0/gotrash_Darwin_x86_64.tar.gz"
      sha256 "16f32b26132fb38e8e8194c533d0b0030c912a4500a32b5ab677dd8a598fc112"

      def install
        bin.install "gotrash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.2.0/gotrash_Darwin_arm64.tar.gz"
      sha256 "9de2e8c48fe9275e957a98b1f0c6a251065cc3e6f21921f3cc202a43a1a4f3f5"

      def install
        bin.install "gotrash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.2.0/gotrash_Linux_arm64.tar.gz"
      sha256 "fb27ec5926ba7f822d603082d248364c16c72f9ce7a7e681c1f5bed29f2831aa"

      def install
        bin.install "gotrash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.2.0/gotrash_Linux_x86_64.tar.gz"
      sha256 "87830d68d44f7a16bd0999bd4329cbc73e478f7600688d6b04dd6ad9a2f0019c"

      def install
        bin.install "gotrash"
      end
    end
  end
end
