# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotrash < Formula
  desc ""
  homepage ""
  version "0.9.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.9.2/gotrash_Darwin_x86_64.tar.gz"
      sha256 "a3c1d9ffcd6e85603f421b5c913c70bc0bb3a8bdf02a8cd3953872705f45ce9f"

      def install
        bin.install "gotrash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.9.2/gotrash_Darwin_arm64.tar.gz"
      sha256 "a3bced16b5d909a793d459495db751d761e68366308ae3f6556c096ac7d8cec2"

      def install
        bin.install "gotrash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.9.2/gotrash_Linux_x86_64.tar.gz"
      sha256 "6437bfbaf5be02bdcb8affb7311c751e07b19c5b7f09bb9f1d4c6405ad446c8f"
      def install
        bin.install "gotrash"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.9.2/gotrash_Linux_arm64.tar.gz"
      sha256 "4e47d2c90fceaa59654150bc66929a708ba3bba565c3d2134e4d8cadeda91f17"
      def install
        bin.install "gotrash"
      end
    end
  end
end
