# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCli < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/hello-cli/releases/download/v0.2.0/hello-cli_Darwin_arm64.tar.gz"
      sha256 "605c1e0fcc5a791af1aa2ea4ec68a0e74427c8e03da4268bc209ab2689542122"

      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/hello-cli/releases/download/v0.2.0/hello-cli_Darwin_x86_64.tar.gz"
      sha256 "235d2cd4dda6f56ca93f6af94620ea07068769bf0c9a04c27614598860be0c34"

      def install
        bin.install "hello-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/hello-cli/releases/download/v0.2.0/hello-cli_Linux_x86_64.tar.gz"
      sha256 "30105dc5c2a3257abdda53ea566a0a54294852108f93a96923963fddc5abad6e"

      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/hello-cli/releases/download/v0.2.0/hello-cli_Linux_arm64.tar.gz"
      sha256 "a4369ee9e9fdb81960d6d6874809d20ac717bb122522494a046cee7e4b27ec14"

      def install
        bin.install "hello-cli"
      end
    end
  end
end
