# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCli < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/hello-cli/releases/download/v0.3.0/hello-cli_Darwin_arm64.tar.gz"
      sha256 "c89d69cfa713d740c84bb73900ca987a771bae34ee4099ece4dac9931c74be6a"

      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/hello-cli/releases/download/v0.3.0/hello-cli_Darwin_x86_64.tar.gz"
      sha256 "e58bc73da3615884a7803341a90a5690c1cd9212b6be60a03d17621a89d7121b"

      def install
        bin.install "hello-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/hello-cli/releases/download/v0.3.0/hello-cli_Linux_x86_64.tar.gz"
      sha256 "c4e2087c845bce4750585cb1479e2b9432d032ef3268415ad1f7f5b99841f9da"

      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/hello-cli/releases/download/v0.3.0/hello-cli_Linux_arm64.tar.gz"
      sha256 "98f7be0419c9c43159c4d685d1c09b08e5cec3b58593da267c8396ce8ff7211d"

      def install
        bin.install "hello-cli"
      end
    end
  end
end
