# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kansai < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/kansai/releases/download/v0.1.0/kansai_Darwin_arm64.tar.gz"
      sha256 "29573d65dc9395cc89be0c6e4576e44c04669cb157c3d89472ae2344ceecd7ad"

      def install
        bin.install "kansai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/kansai/releases/download/v0.1.0/kansai_Darwin_x86_64.tar.gz"
      sha256 "c2b723de042b94896f03bf7e0b2d5d37cf52a2d0511b417b1b6cfb04b5034167"

      def install
        bin.install "kansai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/kansai/releases/download/v0.1.0/kansai_Linux_arm64.tar.gz"
      sha256 "76428d14f947214c8ac8413693b1d4f3d1a20eab6df4868bf9e08fbda693c689"

      def install
        bin.install "kansai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/kansai/releases/download/v0.1.0/kansai_Linux_x86_64.tar.gz"
      sha256 "18d3e262ef7cfa396078b520cd855a3c825087e6fe1fa492254e6ad1a21119de"

      def install
        bin.install "kansai"
      end
    end
  end
end
