# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mingo < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/mingo/releases/download/v0.2.0/mingo_Darwin_arm64.tar.gz"
      sha256 "5878c5dd2bddf1546810e8cfcda1f7f1c0e48517eb5640456e8ad598678db7b3"

      def install
        bin.install "mingo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/mingo/releases/download/v0.2.0/mingo_Darwin_x86_64.tar.gz"
      sha256 "a59509432361aafb55bdb2844a6977998521ea176485ff8106d067fb0f1f753e"

      def install
        bin.install "mingo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/mingo/releases/download/v0.2.0/mingo_Linux_arm64.tar.gz"
      sha256 "ba6b820ae52c60bf5af81ef17d90a6c8aa6f93a35709f2afe9cdf4771fd6944e"

      def install
        bin.install "mingo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/mingo/releases/download/v0.2.0/mingo_Linux_x86_64.tar.gz"
      sha256 "3fd9b52ac2e5351cf29ab0e5a4fdcc2744da6c77e861709a9fa7ea116763c76f"

      def install
        bin.install "mingo"
      end
    end
  end
end
