# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mingo < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/mingo/releases/download/v0.1.0/mingo_Darwin_arm64.tar.gz"
      sha256 "ed963853feefa86ca910d0b91e53cd15f175e92547cdbcec97524b8bf3b3fe5d"

      def install
        bin.install "mingo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/mingo/releases/download/v0.1.0/mingo_Darwin_x86_64.tar.gz"
      sha256 "01c7c807c2fa32b791447b7513911f2e2d08ce03f0bf0b6e979018a6d23dea04"

      def install
        bin.install "mingo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/mingo/releases/download/v0.1.0/mingo_Linux_arm64.tar.gz"
      sha256 "af2f21f43e6ee253e2ab5bac2f5100a02349b28c9e3780f4da6071a517650753"

      def install
        bin.install "mingo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/mingo/releases/download/v0.1.0/mingo_Linux_x86_64.tar.gz"
      sha256 "448b7fd31c2d579471a0f5d5e68766823e3c5a206a57aca769e217f95df9340e"

      def install
        bin.install "mingo"
      end
    end
  end
end
