# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moview < Formula
  desc ""
  homepage ""
  version "0.1.0"

  depends_on "ffmpeg"

  on_macos do
    on_intel do
      url "https://github.com/koki-develop/moview/releases/download/v0.1.0/moview_Darwin_x86_64.tar.gz"
      sha256 "ab1986b8f5bbddda28505f1268a66fdbfeb7fae5edca83537f503e42a2ecf10d"

      def install
        bin.install "moview"
      end
    end
    on_arm do
      url "https://github.com/koki-develop/moview/releases/download/v0.1.0/moview_Darwin_arm64.tar.gz"
      sha256 "fc029cbf09f93a6f367656432d89cc97decff438f7b61b1489c788d733577fa8"

      def install
        bin.install "moview"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koki-develop/moview/releases/download/v0.1.0/moview_Linux_x86_64.tar.gz"
        sha256 "3d811aa511ab8859d83408c77e8a20664cedcaa83bf2575a885fbca54942427e"

        def install
          bin.install "moview"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koki-develop/moview/releases/download/v0.1.0/moview_Linux_arm64.tar.gz"
        sha256 "7e9880d97e9c67ecb7f274969f2e5645bfe55afdd5f2fdadf24fdb7fbe5b5886"

        def install
          bin.install "moview"
        end
      end
    end
  end
end
