# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moview < Formula
  desc ""
  homepage ""
  version "0.1.2"

  depends_on "ffmpeg"

  on_macos do
    on_intel do
      url "https://github.com/koki-develop/moview/releases/download/v0.1.2/moview_Darwin_x86_64.tar.gz"
      sha256 "538c207674d2c2553425fe446cc262cf366a1da31d29be4986b87ef5c197b9d7"

      def install
        bin.install "moview"
      end
    end
    on_arm do
      url "https://github.com/koki-develop/moview/releases/download/v0.1.2/moview_Darwin_arm64.tar.gz"
      sha256 "538b7c18a1cf631284fd5a3af5c7c25bb0ad5ec9725ea5b4e8ac8556ceaea5ba"

      def install
        bin.install "moview"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koki-develop/moview/releases/download/v0.1.2/moview_Linux_x86_64.tar.gz"
        sha256 "20191fc7ccd78d086a6405c531f6f73c03b66a7ec89dbe0b8b6eafa4dea72cf1"

        def install
          bin.install "moview"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koki-develop/moview/releases/download/v0.1.2/moview_Linux_arm64.tar.gz"
        sha256 "49bc791a5523da7ea9e789b40f6fd660113bd416e536398147e043017c6b006b"

        def install
          bin.install "moview"
        end
      end
    end
  end
end
