# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ollamit < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/koki-develop/ollamit/releases/download/v0.1.0/ollamit_Darwin_x86_64.tar.gz"
      sha256 "eb4a0e27d9e457b9d7e86099ffaf0da0afbbac89ec46b1789ece3c058c137af2"

      def install
        bin.install "ollamit"
      end
    end
    on_arm do
      url "https://github.com/koki-develop/ollamit/releases/download/v0.1.0/ollamit_Darwin_arm64.tar.gz"
      sha256 "291840ddf86aa0e683a2b15749c6ff13a2f81e109fa24359b54c7f660698450b"

      def install
        bin.install "ollamit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koki-develop/ollamit/releases/download/v0.1.0/ollamit_Linux_x86_64.tar.gz"
        sha256 "6f74fe3f68c93451e1fe99724b971b878286c19eb72981ba343f97a0cd73b169"

        def install
          bin.install "ollamit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koki-develop/ollamit/releases/download/v0.1.0/ollamit_Linux_arm64.tar.gz"
        sha256 "6504c214e9970936f65ceb1b29b903a6dfd7acfb54206e15a66a1a7de314bdbd"

        def install
          bin.install "ollamit"
        end
      end
    end
  end
end
