# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QiitaCli < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/qiita-cli/releases/download/v0.0.1/qiita-cli_Darwin_arm64.tar.gz"
      sha256 "acee347e9d2b649c118a7056bf97f5260515a64c49b7f4d322837a4cb38d6f8d"

      def install
        bin.install "qiita-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/qiita-cli/releases/download/v0.0.1/qiita-cli_Darwin_x86_64.tar.gz"
      sha256 "cbb17e690f9b9a2279cb2160a0e0662550757aea65cd7b8bc8a5b35982e524fa"

      def install
        bin.install "qiita-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/qiita-cli/releases/download/v0.0.1/qiita-cli_Linux_x86_64.tar.gz"
      sha256 "c426cb1840c6b526cff6e5fb10cd917941583d0f52b0cd85f9d3fcd5f6c9e3ac"

      def install
        bin.install "qiita-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/qiita-cli/releases/download/v0.0.1/qiita-cli_Linux_arm64.tar.gz"
      sha256 "0763c4545d97f947713c6d19b55472cfbaddd315763b5c8cb7bbf6d646d4fb1f"

      def install
        bin.install "qiita-cli"
      end
    end
  end
end
