# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qiita < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/qiita-cli/releases/download/v0.0.3/qiita_Darwin_x86_64.tar.gz"
      sha256 "99cbc0872caa3cb408dd17cc25da44a0f0347689a4a92e3fd185a27c37176911"

      def install
        bin.install "qiita"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/qiita-cli/releases/download/v0.0.3/qiita_Darwin_arm64.tar.gz"
      sha256 "ee03da6d90109a29cb4f8f59351083ba187001c469fbbeb2bf3333c4e284b61e"

      def install
        bin.install "qiita"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/qiita-cli/releases/download/v0.0.3/qiita_Linux_x86_64.tar.gz"
      sha256 "06d517aa55801585ac42c971af467b4d75ea8a8d6c5e2f82461fb278bd7f0b6e"

      def install
        bin.install "qiita"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/qiita-cli/releases/download/v0.0.3/qiita_Linux_arm64.tar.gz"
      sha256 "dc83263c1cddbec0347e388e2ab83613042fb1fd70fc091cea45ce9fe000ab98"

      def install
        bin.install "qiita"
      end
    end
  end
end
