# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sheep < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/sheep/releases/download/v0.1.0/sheep_Darwin_x86_64.tar.gz"
      sha256 "d18c4e1bb60f641dbfbd44744210dd776732221a247ecadd7447656754d4643b"

      def install
        bin.install "sheep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/sheep/releases/download/v0.1.0/sheep_Darwin_arm64.tar.gz"
      sha256 "853aba6b0c18ee45b3ec748bbaa109e719c2dd5e91cf0dc9b6494524c2bbe816"

      def install
        bin.install "sheep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/sheep/releases/download/v0.1.0/sheep_Linux_arm64.tar.gz"
      sha256 "98428296df3fe8df5aae6ee4beeb350c9032512597c5d03f85ff77c4455e5f71"

      def install
        bin.install "sheep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/sheep/releases/download/v0.1.0/sheep_Linux_x86_64.tar.gz"
      sha256 "3cbcca980f5fbb7daf7392d0095ab7c0dec22f12aa2831fec19f14621c58fe8f"

      def install
        bin.install "sheep"
      end
    end
  end
end
