# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sheep < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/sheep/releases/download/v0.2.0/sheep_Darwin_arm64.tar.gz"
      sha256 "37a9a29e3e0212906856caf4028c1167f652e53a69e8aca502da25c9000bdaaa"

      def install
        bin.install "sheep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/sheep/releases/download/v0.2.0/sheep_Darwin_x86_64.tar.gz"
      sha256 "e62555b00348bcf6e3f081ebe001938cd8b457f723cee21d065ac00e055fbd20"

      def install
        bin.install "sheep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/sheep/releases/download/v0.2.0/sheep_Linux_arm64.tar.gz"
      sha256 "03f339495fbb98eded67f1e5de5f91cfccc4b4cb1598e84ea6e23be1810145ce"

      def install
        bin.install "sheep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/sheep/releases/download/v0.2.0/sheep_Linux_x86_64.tar.gz"
      sha256 "7188ac58496424bb93822f165f23ca1f2cab295c5775027797f0730335180acf"

      def install
        bin.install "sheep"
      end
    end
  end
end
