# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slp < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/slp/releases/download/v0.3.0/slp_Darwin_arm64.tar.gz"
      sha256 "0aebbd23a68584acbd751efbcab643611aa9c9c0e022c16df951ed5de56b98c6"

      def install
        bin.install "slp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/slp/releases/download/v0.3.0/slp_Darwin_x86_64.tar.gz"
      sha256 "d48c58d57debd091b28b4ff265ac366d769e3ed4f9f810e2dd6aafade3fe1a37"

      def install
        bin.install "slp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/slp/releases/download/v0.3.0/slp_Linux_arm64.tar.gz"
      sha256 "5438f669e039d86b65bf1ab1ee07d1e2beaf2159d0b994f61a77614e63b13c3c"

      def install
        bin.install "slp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/slp/releases/download/v0.3.0/slp_Linux_x86_64.tar.gz"
      sha256 "cdee57a2cf40bddcab6af37dbef74623ed50606f0263e6a0fd7e1ab5806bf394"

      def install
        bin.install "slp"
      end
    end
  end
end
