# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slp < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/slp/releases/download/v0.2.0/slp_Darwin_x86_64.tar.gz"
      sha256 "b1015a79c0c460400f57127fcd0bb6fcd9b8841157cf7348540b401c9787aadb"

      def install
        bin.install "slp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/slp/releases/download/v0.2.0/slp_Darwin_arm64.tar.gz"
      sha256 "01ea3f111bd524c53846b6a7a8baf1af8bd98e13fa8d93e426c92b946844a646"

      def install
        bin.install "slp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/slp/releases/download/v0.2.0/slp_Linux_x86_64.tar.gz"
      sha256 "67940568e734e0f2dba5141280281353021f7d9e0a736f9a6ec6600bfb5e1ae2"

      def install
        bin.install "slp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/slp/releases/download/v0.2.0/slp_Linux_arm64.tar.gz"
      sha256 "193d978a0030486fec0f7d17f3fa1596600b56a0fdfc6a2a6e840bad37cab838"

      def install
        bin.install "slp"
      end
    end
  end
end
