# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slp < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/slp/releases/download/v0.1.0/slp_Darwin_x86_64.tar.gz"
      sha256 "198fe2248414ffe3f1b0ee3fbf91939de18adfa930b216da071d5f5473f37e63"

      def install
        bin.install "slp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/slp/releases/download/v0.1.0/slp_Darwin_arm64.tar.gz"
      sha256 "8c1b375f6341080099af61a8462de9ddd32ff271e3a68bfdc5170c984deebb1a"

      def install
        bin.install "slp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/slp/releases/download/v0.1.0/slp_Linux_x86_64.tar.gz"
      sha256 "85706d633365ba06dffe2ee30d1905c8e88682f27f1cfec09f83baf7587b85e1"

      def install
        bin.install "slp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/slp/releases/download/v0.1.0/slp_Linux_arm64.tar.gz"
      sha256 "63e41c08bc50bab9cdca4becb79a596558240a3d1073c98be6c784ea4a8b0ceb"

      def install
        bin.install "slp"
      end
    end
  end
end
