# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoistCli < Formula
  desc ""
  homepage ""
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/todoist-cli/releases/download/v0.6.0/todoist-cli_Darwin_x86_64.tar.gz"
      sha256 "f3af92bb95ce20fda7f697019b67fdca37d0b0424f58b283cd1381a6de85fc40"

      def install
        bin.install "todoist-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/todoist-cli/releases/download/v0.6.0/todoist-cli_Darwin_arm64.tar.gz"
      sha256 "7f9b5d801831101306476e64f21316904471060e54ec0991e83335e86edd03d5"

      def install
        bin.install "todoist-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/todoist-cli/releases/download/v0.6.0/todoist-cli_Linux_x86_64.tar.gz"
      sha256 "74267e3b50fb95ac90a70495774a3dc8c5a7d54ac173934a59efef09afc0105d"

      def install
        bin.install "todoist-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/todoist-cli/releases/download/v0.6.0/todoist-cli_Linux_arm64.tar.gz"
      sha256 "632b925a55c1dceed083b04e9ca1145fe4db232aea6ee5a2bfca052d0c61e0dd"

      def install
        bin.install "todoist-cli"
      end
    end
  end
end
