# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoistCli < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/todoist-cli/releases/download/v0.2.0/todoist-cli_Darwin_arm64.tar.gz"
      sha256 "c9c6adcdf0800bab618cbf86d2f390b2a068cc50950ffe4e72f556f4253903b8"

      def install
        bin.install "todoist-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/todoist-cli/releases/download/v0.2.0/todoist-cli_Darwin_x86_64.tar.gz"
      sha256 "d77469691b8e93eb542ee0a44ea8412d78c792baf5e4cf6d750a38342f59f67d"

      def install
        bin.install "todoist-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/todoist-cli/releases/download/v0.2.0/todoist-cli_Linux_arm64.tar.gz"
      sha256 "cc15dc067a9c47e656e06425fa0b7751712aed2ab94279165ac9fe23f4d91c8d"

      def install
        bin.install "todoist-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/todoist-cli/releases/download/v0.2.0/todoist-cli_Linux_x86_64.tar.gz"
      sha256 "ee33730c23f1d6891605e2d1cde4d43bfca26a02c79c8772a5820751d79f3399"

      def install
        bin.install "todoist-cli"
      end
    end
  end
end
