# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typingo < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/typingo/releases/download/v0.2.0/typingo_Darwin_x86_64.tar.gz"
      sha256 "f00358e5c00d7f599c24ffa4108aab87b09e12cd657326d29083a91a10261ca0"

      def install
        bin.install "typingo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/typingo/releases/download/v0.2.0/typingo_Darwin_arm64.tar.gz"
      sha256 "93b77a8dac3d34389f45d3dedd355c0ec195451cd6554fb8c7c6610542e9f576"

      def install
        bin.install "typingo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/typingo/releases/download/v0.2.0/typingo_Linux_arm64.tar.gz"
      sha256 "d42b7169e97252ba74e7d88e05229ca89167fc31fc1f2c06f23bbbe1f7029cfe"

      def install
        bin.install "typingo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/typingo/releases/download/v0.2.0/typingo_Linux_x86_64.tar.gz"
      sha256 "39bb5a64fb204b8afcbe157a942a3a1428baa06c7ae2165f341168c8f469b32c"

      def install
        bin.install "typingo"
      end
    end
  end
end
