# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clive < Formula
  desc "Automates terminal operations and lets you view them live via a browser"
  homepage "https://github.com/koki-develop/clive"
  version "0.12.12"

  depends_on "ttyd"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/clive/releases/download/v0.12.12/clive_Darwin_x86_64.tar.gz"
      sha256 "ba762b270ab64ec61f463bb62cea5df5b1a5fe8198d02c0928740745915fb3a6"

      def install
        bin.install "clive"
        bash_completion.install "completions/clive.bash" => "clive"
        zsh_completion.install "completions/clive.zsh" => "_clive"
        fish_completion.install "completions/clive.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/clive/releases/download/v0.12.12/clive_Darwin_arm64.tar.gz"
      sha256 "2baa3122bed0f803a6850c541090774bdbfc05b634be93e2b637e41451bc5ed5"

      def install
        bin.install "clive"
        bash_completion.install "completions/clive.bash" => "clive"
        zsh_completion.install "completions/clive.zsh" => "_clive"
        fish_completion.install "completions/clive.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/clive/releases/download/v0.12.12/clive_Linux_x86_64.tar.gz"
      sha256 "3f63c43e5b3bef48ba98d946df8ef9eadc0faf5086d1e3d8facc35408444a1d6"
      def install
        bin.install "clive"
        bash_completion.install "completions/clive.bash" => "clive"
        zsh_completion.install "completions/clive.zsh" => "_clive"
        fish_completion.install "completions/clive.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/clive/releases/download/v0.12.12/clive_Linux_arm64.tar.gz"
      sha256 "1792babd0119a0c808611cc65513675d8527874cdff59f5238ec3789f3ab997b"
      def install
        bin.install "clive"
        bash_completion.install "completions/clive.bash" => "clive"
        zsh_completion.install "completions/clive.zsh" => "_clive"
        fish_completion.install "completions/clive.fish"
      end
    end
  end

  test do
    system "#{bin}/clive", "init"
    system "#{bin}/clive", "validate"
    assert_match "clive version v#{version}", shell_output("#{bin}/clive --version")
  end
end
