# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clive < Formula
  desc "Automates terminal operations and lets you view them live via a browser"
  homepage "https://github.com/koki-develop/clive"
  version "0.12.15"

  depends_on "ttyd"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/clive/releases/download/v0.12.15/clive_Darwin_x86_64.tar.gz"
      sha256 "5f0300ec054590ace8db2cd475022666b6db6743e39a86d44ab10a84deafafa3"

      def install
        bin.install "clive"
        bash_completion.install "completions/clive.bash" => "clive"
        zsh_completion.install "completions/clive.zsh" => "_clive"
        fish_completion.install "completions/clive.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/clive/releases/download/v0.12.15/clive_Darwin_arm64.tar.gz"
      sha256 "53a127a19139fab90a5bd123e27167c7e3c431ae514bfcc8c85b00608ddcb783"

      def install
        bin.install "clive"
        bash_completion.install "completions/clive.bash" => "clive"
        zsh_completion.install "completions/clive.zsh" => "_clive"
        fish_completion.install "completions/clive.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/clive/releases/download/v0.12.15/clive_Linux_x86_64.tar.gz"
      sha256 "45cf9ecc48f4e71437ad5e6ba0e55776d467cebd602c534e4db3c36720766109"
      def install
        bin.install "clive"
        bash_completion.install "completions/clive.bash" => "clive"
        zsh_completion.install "completions/clive.zsh" => "_clive"
        fish_completion.install "completions/clive.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/clive/releases/download/v0.12.15/clive_Linux_arm64.tar.gz"
      sha256 "17f63337164ac0a59bd1f5bd81f93a8e788580c78c130abf68afede2711c6839"
      def install
        bin.install "clive"
        bash_completion.install "completions/clive.bash" => "clive"
        zsh_completion.install "completions/clive.zsh" => "_clive"
        fish_completion.install "completions/clive.fish"
      end
    end
  end

  test do
    system "#{bin}/clive", "init"
    system "#{bin}/clive", "validate"
    assert_match "clive version v#{version}", shell_output("#{bin}/clive --version")
  end
end
