# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddsk < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/ddsk/releases/download/v0.1.0/ddsk_Darwin_x86_64.tar.gz"
      sha256 "7f1a14ef34c5fa2da445f6627a974c16d6919ec84994b3a45cdbb171238367f1"

      def install
        bin.install "ddsk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/ddsk/releases/download/v0.1.0/ddsk_Darwin_arm64.tar.gz"
      sha256 "9c5ee0e66d3f5d031290357a272eab64c1fdfebad1a64dd530e3fb870b3c8820"

      def install
        bin.install "ddsk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/ddsk/releases/download/v0.1.0/ddsk_Linux_arm64.tar.gz"
      sha256 "4c5dd4397bacdd5177f22533b19341439f5d215903d793b4b9069dddfb54ef73"

      def install
        bin.install "ddsk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/ddsk/releases/download/v0.1.0/ddsk_Linux_x86_64.tar.gz"
      sha256 "5ee3cede516acecfbe42c6f8d441c4045321aa53b198b95cf5d0b6b8af877426"

      def install
        bin.install "ddsk"
      end
    end
  end
end
