# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gat < Formula
  desc ""
  homepage ""
  version "0.30.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gat/releases/download/v0.30.2/gat_Darwin_x86_64.tar.gz"
      sha256 "961b41add46d668d8dbddc1ed547dc9ce23175ee52b4464fbb0761e05675d471"

      def install
        bin.install "gat"
        bash_completion.install "completions/gat.bash" => "gat"
        zsh_completion.install "completions/gat.zsh" => "_gat"
        fish_completion.install "completions/gat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/gat/releases/download/v0.30.2/gat_Darwin_arm64.tar.gz"
      sha256 "5e95249b5b26410876f1ca8643b4e0a2e0ffb0d25fb68fcd4d3522a894eba842"

      def install
        bin.install "gat"
        bash_completion.install "completions/gat.bash" => "gat"
        zsh_completion.install "completions/gat.zsh" => "_gat"
        fish_completion.install "completions/gat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gat/releases/download/v0.30.2/gat_Linux_x86_64.tar.gz"
      sha256 "e5dd55992f4431e57bdb6eb671f63b7b127696e270a66ad42ea9502459e96a3f"
      def install
        bin.install "gat"
        bash_completion.install "completions/gat.bash" => "gat"
        zsh_completion.install "completions/gat.zsh" => "_gat"
        fish_completion.install "completions/gat.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gat/releases/download/v0.30.2/gat_Linux_arm64.tar.gz"
      sha256 "9df4443375436fcb2332f8a62ff2b850f727d81960a9e69378b763d4c36fc1d5"
      def install
        bin.install "gat"
        bash_completion.install "completions/gat.bash" => "gat"
        zsh_completion.install "completions/gat.zsh" => "_gat"
        fish_completion.install "completions/gat.fish"
      end
    end
  end
end
