# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gat < Formula
  desc ""
  homepage ""
  version "0.25.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gat/releases/download/v0.25.1/gat_Darwin_x86_64.tar.gz"
      sha256 "9e46bf87cd1680fbeea9d0cebd1c6ecdf38138db60a85a90454f91daf65ba571"

      def install
        bin.install "gat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/gat/releases/download/v0.25.1/gat_Darwin_arm64.tar.gz"
      sha256 "c86463394a7c7806af08c29d2b8e360a86f0043c43b958529fbed3b08fe7218b"

      def install
        bin.install "gat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gat/releases/download/v0.25.1/gat_Linux_x86_64.tar.gz"
      sha256 "eb8ffb370b54eea9e4e6b30f75771cbe6de3921a4cbe7fcb2bea22e37ff0d207"
      def install
        bin.install "gat"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gat/releases/download/v0.25.1/gat_Linux_arm64.tar.gz"
      sha256 "4a02b3efeb59fe27665bf13b341fc48174b155582e615aa587782e7e7f9708cd"
      def install
        bin.install "gat"
      end
    end
  end
end
