# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gat < Formula
  desc ""
  homepage ""
  version "0.25.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gat/releases/download/v0.25.8/gat_Darwin_x86_64.tar.gz"
      sha256 "c7920b1d8df7a52ee9ae4c67c550aef926817d7418afebbd0620dd5b8b01afeb"

      def install
        bin.install "gat"
        bash_completion.install "completions/gat.bash" => "gat"
        zsh_completion.install "completions/gat.zsh" => "_gat"
        fish_completion.install "completions/gat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/gat/releases/download/v0.25.8/gat_Darwin_arm64.tar.gz"
      sha256 "5b94621f38ac4e7e5c7e38ee68070ef7f751b0c9dcf2db8a7f4f866ee894ddee"

      def install
        bin.install "gat"
        bash_completion.install "completions/gat.bash" => "gat"
        zsh_completion.install "completions/gat.zsh" => "_gat"
        fish_completion.install "completions/gat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gat/releases/download/v0.25.8/gat_Linux_x86_64.tar.gz"
      sha256 "170c4c6c8ee34d22b32fbbc7a32c354b5c2874bb9aba986322549d8c97e3f6c7"
      def install
        bin.install "gat"
        bash_completion.install "completions/gat.bash" => "gat"
        zsh_completion.install "completions/gat.zsh" => "_gat"
        fish_completion.install "completions/gat.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gat/releases/download/v0.25.8/gat_Linux_arm64.tar.gz"
      sha256 "76535d2bd3c5bac5a8346d08469149352063ee958f1af3c654453181bcf483e9"
      def install
        bin.install "gat"
        bash_completion.install "completions/gat.bash" => "gat"
        zsh_completion.install "completions/gat.zsh" => "_gat"
        fish_completion.install "completions/gat.fish"
      end
    end
  end
end
