# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofzf < Formula
  desc ""
  homepage ""
  version "0.15.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.15.0/gofzf_Darwin_arm64.tar.gz"
      sha256 "d482c389d282049573bdc40c4e79910a6f489649cc423efc99ad89d8d385480f"

      def install
        bin.install "gofzf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.15.0/gofzf_Darwin_x86_64.tar.gz"
      sha256 "89aef0d8f422a91da342946caf159f72a76e0c784c7c7aaa8cdae244fb57b2de"

      def install
        bin.install "gofzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.15.0/gofzf_Linux_x86_64.tar.gz"
      sha256 "49e3ce8864feedde91c03dcfd42eaaf963fd933b176a51e3915a6eb39adc662b"

      def install
        bin.install "gofzf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/go-fzf/releases/download/v0.15.0/gofzf_Linux_arm64.tar.gz"
      sha256 "4556453c7797fb3f91e8de98b2576eae8785205d7c48f5896425ae5bdd9d0d03"

      def install
        bin.install "gofzf"
      end
    end
  end
end
