# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotrash < Formula
  desc ""
  homepage ""
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.10.0/gotrash_Darwin_x86_64.tar.gz"
      sha256 "32eb4e5c8fbdbca3dc1c1e35d0e00de0214a6e633cbff6c01bf1be81ccadb014"

      def install
        bin.install "gotrash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.10.0/gotrash_Darwin_arm64.tar.gz"
      sha256 "362ea5b22c954e46143563764b0e4115ebf66db63d46538f5a08f10b0dc7fee5"

      def install
        bin.install "gotrash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.10.0/gotrash_Linux_x86_64.tar.gz"
      sha256 "40fae370b481e9c64d37da4251e4261352ee017db015e4749af6e6712f5a751e"
      def install
        bin.install "gotrash"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/koki-develop/gotrash/releases/download/v0.10.0/gotrash_Linux_arm64.tar.gz"
      sha256 "3ab5554f4d623e929f236d02afcaeca99ea2d3a6046b540500f404354b90a246"
      def install
        bin.install "gotrash"
      end
    end
  end
end
