# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ollamit < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/koki-develop/ollamit/releases/download/v0.1.1/ollamit_Darwin_x86_64.tar.gz"
      sha256 "4e4ab09aa0de4a62488126d8b5a543267cbd05cb3fc9c8537e9558cfeedb4022"

      def install
        bin.install "ollamit"
      end
    end
    on_arm do
      url "https://github.com/koki-develop/ollamit/releases/download/v0.1.1/ollamit_Darwin_arm64.tar.gz"
      sha256 "36ccd3afe1fb64bc825187199e798b557ce611008ca1d1e0bb4ab89d0b2a8f62"

      def install
        bin.install "ollamit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koki-develop/ollamit/releases/download/v0.1.1/ollamit_Linux_x86_64.tar.gz"
        sha256 "a86752df467b2d78e37a1180c79bdfa396904859d6bcfce84e9169a67c85db11"

        def install
          bin.install "ollamit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koki-develop/ollamit/releases/download/v0.1.1/ollamit_Linux_arm64.tar.gz"
        sha256 "e3d31ab157bbb016844a4ef69e62e515f5a2ccfcdcb2ea95fac3d81970f842dc"

        def install
          bin.install "ollamit"
        end
      end
    end
  end
end
